application: jushaps
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /.*
  script: main.app
#- url: /(.*\.(gif|png|jpg))$
#  static_files: images/\1
#  upload: images/.*\.(gif|png|jpg)$

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest